kind: Pod
apiVersion: v1
metadata:
  name: echo-pod
spec:
  containers:
  - name: echo
    image: hashicorp/http-echo:0.2.3
    imagePullPolicy: IfNotPresent
    command: 
    - "/http-echo"
    ports:
    - containerPort: 8080
    args:
    - "-listen=0.0.0.0:8080"
    - "-text=foo"
